name: "Antora Site"
description: "Generate the Antora site"
inputs:
  antora_playbook:
    description: 'The Antora playbook file'
    required: true
    default: 'site.yaml'
  site_sources_path:
    description: 'The path relative to workspace root, where the asciidoc sources exits'
    required: true
    default: "${{ github.workspace }}"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
     - ${{ inputs.antora_playbook}}
     - ${{ inputs.site_sources_path }}